# Combining Data

Practice combining data from two different data sets. In the same folder as this Jupyter notebook, there are two csv files:
* rural_population_percent.csv
* electricity_access_percent.csv

They both come from the World Bank Indicators data. 
* https://data.worldbank.org/indicator/SP.RUR.TOTL.ZS
* https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS

The rural populaton data represents the percent of a country's population that is rural over time. The electricity access data shows the percentage of people with access to electricity.

In this exercise, you will combine these two data sets together into one pandas data frame.

# Exercise 1

Combine the two data sets using the [pandas concat method](https://pandas.pydata.org/pandas-docs/stable/merging.html). In other words, find the union of the two data sets.

In [16]:
# TODO: import the pandas library
import pandas as pd
# TODO: read in each csv file into a separate variable
# HINT: remember from the Extract material that these csv file have some formatting issues
# HINT: The file paths are 'rural_population_percent.csv' and 'electricity_access_percent.csv'
df_rural = pd.read_csv('rural_population_percent.csv', skiprows=list(range(2,6)))
df_electricity = pd.read_csv('electricity_access_percent.csv', skiprows= list(range(2,6)))

# TODO: remove the 'Unnamed:62' column from each data set
df_rural = df_rural.drop('Unnamed: 62', axis=1)
df_electricity = df_electricity.drop('Unnamed: 62', axis=1)
# TODO: combine the two data sets together using the concat method

#df = pd.concat([df_rural, df_electricity])
# In other words, all of the rows of df_rural will come first
# followed by all the rows in df_electricity. This is possible to do
# because they both have the same column names.

KeyError: "['Unnamed: 62'] not found in axis"

In [17]:
df_rural.sample(10)

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Data Source,World Development Indicators,Unnamed: 2
Angola,AGO,Rural population (% of total population),SP.RUR.TOTL.ZS,89.565000,89.202000,88.796000,88.376000,87.942000,87.496000,87.035000,86.559000,86.068000,85.564000,85.043000,84.566000,84.125000,83.676000,83.215000,82.745000,82.263000,81.772000,81.270000,80.758000,80.234000,79.701000,79.157000,78.602000,78.035000,77.459000,76.872000,76.275000,75.666000,75.048000,74.418000,73.779000,73.128000,72.470000,71.800000,71.120000,70.430000,69.732000,69.025000,68.308000,67.581000,66.848000,66.105000,65.355000,64.595000,63.831000,63.058000,62.278000,61.491000,60.701000,59.903000,59.100000,58.301000,57.510000,56.726000,55.950000,55.181000,54.422000,NaN
Romania,ROU,Rural population (% of total population),SP.RUR.TOTL.ZS,65.791000,65.106000,64.414000,63.716000,63.011000,62.303000,61.655000,61.165000,60.672000,60.178000,59.681000,59.182000,58.681000,58.179000,57.675000,57.169000,56.661000,56.058000,55.351000,54.642000,53.930000,53.219000,52.505000,51.790000,51.074000,50.359000,49.643000,48.927000,48.210000,47.496000,46.783000,46.070000,45.773000,45.926000,46.078000,46.231000,46.384000,46.537000,46.689000,46.842000,46.996000,47.148000,47.220000,47.088000,46.957000,46.826000,46.695000,46.564000,46.433000,46.302000,46.171000,46.040000,45.909000,45.765000,45.607000,45.436000,45.251000,45.053000,NaN
East Asia & Pacific,EAS,Rural population (% of total population),SP.RUR.TOTL.ZS,77.512403,76.863212,76.336665,75.872488,75.397771,75.405964,75.416096,75.373937,75.339139,75.235250,75.162985,75.083224,74.985752,74.829195,74.547968,74.424837,74.265885,74.098131,73.723288,73.127764,72.504420,71.848968,71.194419,70.631952,70.055168,69.473469,68.873428,68.260224,67.640115,67.006088,66.361439,65.669734,64.959018,64.232221,63.485851,62.724589,61.952843,61.184030,60.401548,59.609137,58.789356,57.789664,56.699677,55.608664,54.514411,53.422665,52.364107,51.324799,50.277681,49.241366,48.208773,47.185525,46.187990,45.222282,44.284411,43.375096,42.495860,41.646571,NaN
Mauritania,MRT,Rural population (% of total population),SP.RUR.TOTL.ZS,93.120000,92.565000,91.969000,91.329000,90.643000,89.910000,89.126000,88.288000,87.394000,86.446000,85.436000,84.364000,83.227000,82.029000,80.763000,79.431000,78.029000,76.673000,75.373000,74.025000,72.629000,71.190000,69.705000,68.178000,66.609000,65.006000,63.366000,61.695000,60.218000,59.449000,58.675000,57.896000,57.113000,56.328000,55.538000,54.746000,53.951000,53.155000,52.357000,51.558000,50.756000,49.957000,49.168000,48.390000,47.625000,46.873000,46.134000,45.408000,44.697000,44.000000,43.318000,42.652000,42.000000,41.364000,40.745000,40.141000,39.554000,38.983000,NaN
Monaco,MCO,Rural population (% of total population),SP.RUR.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
"Bahamas, The",BHS,Rural population (% of total population),SP.RUR.TOTL.ZS,40.288000,39.546000,38.807000,38.074000,37.358000,36.657000,35.960000,35.270000,34.584000,33.907000,33.236000,32.571000,31.912000,31.262000,30.619000,29.983000,29.353000,28.734000,28.121000,27.516000,26.898000,26.157000,25.429000,24.715000,24.013000,23.326000,22.653000,21.993000,21.346000,20.716000,20.162000,19.933000,19.707000,19.482000,19.260000,19.039000,18.820000,18.604000,18.389000,18.176000,17.991000,17.936000,17.882000,17.828000,17.774000,17.720000,17.666000,17.612000,17.558000,17.505000,17.451000,17.394000,17.333000,17.268000,17.199000,17.126000,17.049000,16.969000,NaN
South Asia,SAS,Rural population (% of total population),SP.RUR.TOTL.ZS,83.264979,83.133571,82.946153,82.756975,82.561748,82.366251,82.169157,81.969924,81.767404,81.559433,81.344084,81.096634,80.771514,80.440180,80.089782,79.710269,79.324086,78.930220,78.526696,78.111748,77.686524,77.312719,77.060990,76.806110,76.548650,76.290368,76.030314,75.769055,75.505936,75.241867,74.978090,74.727508,74.504762,74.281004,74.054722,73.826171,73.593075,73.357129,73.118551,72.877262,72.633758,72.350692,71.999276,71.643794,71.282776,70.917578,70.547154,70.171048,69.789716,69.405404,69.017292,68.624813,68.223951,67.816073,67.399895,66.975278,66.543482,66.102820,NaN
Gibraltar,GIB,Rural population (% of total population),SP.RUR.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
Singapore,SGP,Rural population (% of total population),SP.RUR.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
Algeria,DZA,Rural population (% of total population),SP.RUR.TOTL.ZS,69.490000,68.203000,66.786000,65.338000,63.859000,62.357000,61.160000,60.996000,60.831000,60.666000,60.500000,60.335000,60.169000,60.003000,59.837000,59.670000,59.503000,59.072000,58.206000,57.335000,56.458000,55.580000,54.697000,53.811000,52.921000,52.032000,51.140000,50.278000,49.489000,48.702000,47.915000,47.129000,46.343000,45.561000,44.781000,44.003000,43.226000,42.456000,41.687000,40.882000,40.081000,39.288000,38.499000,37.716000,36.939000,36.170000,35.407000,34.652000,33.903000,33.178000,32.474000,31.791000,31.130000,30.490000,29.871000,29.273000,28.696000,28.139000,NaN

In [9]:
df_electricity.sample(5)

,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,42.4,44.8548851013184,42.7,43.2220189082037,69.1,67.2595520019531,89.5,71.5,84.1371383666992,Unnamed: 61
250,"Venezuela, RB",VEN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.630798,98.710304,98.807846,98.840000,99.044968,99.178551,99.318146,99.460739,99.603836,NaN
121,St. Kitts and Nevis,KNA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,96.696312,97.215424,97.752556,98.313385,98.864212,99.366478,99.736694,99.930016,100.000000,NaN
42,Comoros,COM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.307968,60.707882,63.125820,65.558777,69.300000,70.457733,72.917725,75.380714,77.844215,NaN
232,Latin America & the Caribbean (IDA & IBRD coun...,TLA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,95.186103,95.441090,95.801052,96.161153,96.522279,96.922377,96.936467,97.183215,97.742979,NaN
165,Malaysia,MYS,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.729248,99.300000,99.289230,99.567345,99.800000,99.929138,99.985123,99.998589,100.000000,NaN

# Exercise 2 (Challenge)

This exercise is more challenging.

Combine the two datas in the csv file together so that the output looks like the following:

|Country Name|Country Code|Year|Rural_Value|Electricity_Value|
|--|--|--|--|--|--|
|Aruba|ABW|1960|49.224|49.239|
... etc.

Order the results in the dataframe by country and then by year

Here are a few pandas methods that should be helpful:
* [melt](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html)
* [drop](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html)
* [merge](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.merge.html)
* [sort_values](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html)

HINT: You can use country name, country code, and the year as common keys between the data sets

In [4]:
# TODO: merge the data sets together according to the instructions. First, use the 
# melt method to change the formatting of each data frame so that it looks like this:
# Country Name, Country Code, Year, Rural Value
# Country Name, Country Code, Year, Electricity Value

# TODO: drop any columns from the data frames that aren't needed

# TODO: merge the data frames together based on their common columns
# in this case, the common columns are Country Name, Country Code, and Year

# TODO: sort the results by country and then by year

df_combined = None